version: '3.9'

services:
  mysql_db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: wp_db
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: 1234
    volumes:
      - db_data1:/var/lib/mysql

  wordpress:
    image: wordpress:latest
    ports:
      - 8000:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql_db:3306
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: 1234
      WORDPRESS_DB_NAME: wp_db
    volumes:
      - ./wordpress-data:/var/www/html
    depends_on:
      - mysql_db

  php_my_admin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql_db
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql_db
      MYSQL_ROOT_PASSWORD: 1234
    # deploy:
    #   replicas: 3

volumes:
  db_data1: {}